module.exports = {
    /**
     * General Translations
     */
    "accept_responses": "Accept Responses?",
    "action_failed": "Failed to perform requested action.",
    "active": "Active",
    "agree_and_continue": "I Understand And Wish To Continue",
    "aggregates": "Side-by-Side Surveys",
    "aggregates_not_found": "We could not find any aggregates for this survey group! Please make sure questions have been mapped from survey to survey.",
    "all": "All",
    "answer": "Answer",
    "answer_distribution": "Answer Distribution",
    "answer_label": "Answer Label",
    "answered": "Answered",
    "apply": "Apply",
    "audit": "Audit",
    "audit_desktop_only": "Audit information is complex, and as such is only available on desktop computers.",
    "available_surveys": "Available Surveys",
    "available_survey_data": "Available Survey Data",
    "background_color": "Background Color",
    "back_to_app": "Back to Application",
    "blockchain_hash_summary": "Blockchain Hash Summary",
    "button_composite_create": "New Composite",
    "button_composite_group_create": "New Composite Group",
    "button_survey_create": "New Survey",
    "button_survey_group_create": "New Survey Group",
    "cache": "Cache",
    "cache_warning": "Click the following button to invalidate your cache. Note that this may inversely alter performance.",
    "calculate_composite": "Calculating composite, please wait...",
    "cancel": "Cancel",
    "close_active": "Survey Closure Active...",
    "composites_all": "All Composites",
    "composite_overall_score": "Overall Composite Score",
    "composite": [
        "Composite",
        "Composites",
    ],
    "composite_group": [
        "Composite Group",
        "Composite Groups"
    ],
    "concluded": "Concluded",
    "confirm_details": "Confirm your details below.",
    "custom_url": "Custom URL",
    "cutoff": "Cut Off",
    "data_point": [
        "Data Point",
        "Data Points",
    ],
    "data_source_id": "Data Source Survey ID",
    "date_start": "Start Accepting Responsed On",
    "date_end": "Stop Accepting Responsed On",
    "date_range_description": "Select the date range in which your survey will be active, collecting responses. Responses received outside of this date range will not be recorded.",
    "date_recorded": "Response Record",
    "date_received_by_sa": "Response Imported",
    "date_received_by_blockchain": "Response Recorded",
    "delete": "Delete",
    "description": "Description",
    "details_additional": "Input additional details.",
    "edit": "Edit",
    "enter_details": "Enter your desired details.",
    "filters": "Filters",
    "formula": "Formula",
    "icon": "Icon",
    "import_active": "Import active...",
    "include_in_numerator_set": "Include in Numerator Set",
    "invalidate": "Invalidate",
    "landing_image": "Landing Page Image",
    "landing_image_description": "Link to an image in JPG, PNG format no larger than 1200x500 pixels in scale.",
    "listener_url": "Listener URL",
    "loading": "Loading",
    "login": "Login",
    "logout": "Logout",
    "make_private": "Making this private will hide it from anyone reading this page, including you. This can be reversed in the settings page. Are you sure you wish to continue?",
    "make_public": "Make Public",
    "meancutoff_error": "Cutoff value is below the minimum value. Please change.",
    "merkle_root": "Merkle Root",
    "misc": "Miscellaneous",
    "name": "Name",
    "next_step": "Next Step",
    "no": "No",
    "none": "None",
    "nothing_to_reorder": "Nothing to re-order!",
    "numerator": [
        "Numerator",
        "Numerators",
    ],
    "password_input_placeholder": "Input Access Password",
    "please_wait": "Please wait, this may take a moment...",
    "preview": "Preview",
    "previous": "Previous",
    "privacy": "Privacy",
    "private_content": "The following content has been marked as \"private\". You can change that below.",
    "question": [
        "Question",
        "Questions",
    ],
    "question_group": [
        "Question Group",
        "Question Groups",
    ],
    "questions_all": "All Questions",
    "responses": "Responses",
    "responses_import": "Import Responses",
    "save": "Save",
    "select_data_point_to_add": "Select a question to add to the composite...",
    "setting": [
        "Setting",
        "Settings",
    ],
    "source": "Source",
    "source_id": "Source ID",
    "source_plugin": "Source Plugin",
    "status": "Status",
    "submit": "Submit",
    "success": "Success",
    "survey": [
        "Survey",
        "Surveys",
    ],
    "survey_add_new": "Add New Survey to Group",
    "survey_group": [
        "Survey Group",
        "Survey Groups",
    ],
    "survey_close": "Close Survey",
    "survey_comparison": "Survey to Survey Comparisons",
    "survey_import_warning": "If your data source contains responses that you'd like to import, please do so below. Remember, This process may take up to SEVERAL HOURS to complete during which LIVE SURVEYS and/or the ACCEPTANCE of REAL TIME DATA may be ADVERSELY AFFECTED.",
    "survey_recent": "Recent Surveys",
    "title": [
        "Title",
        "Titles",
    ],
    "transaction": "Response Record",
    "unique_url_name": "Create a unique name for your dashboard link.",
    "view_full_survey": "View Full Survey",
    "view_survey": "View Survey",
    "view_survey_group": "View Survey Group",
    "warning": "Warning",
    "yes": "Yes",

    /**
     * Error Codes
     */
    "E001": "Generic error, no additional details.",
    "E002": "Survey not found.",
    "E003": "Could not find plugin.",
    "E004": "Survey creation error: does the survey already exist or are required fields missing?",
    "E005": "Survey group not found.",
    "E006": "Error creating survey group.",
    "E007": "Could not register survey response.",
    "E008": "Incorrect survey code.",
    "E009": "Could not find question.",
    "E010": "Could not find survey.",
    "E011": "Survey does not contain any groups.",
    "E012": "Could not find question group.",
    "E013": "Question group does not contain any questions.",
    "E014": "Password is required.",
    "E015": "Incorrect password.",
    "E016": "You cannot access this question's data.",
    "E017": "Error normalizing survey data.",
    "E018": "No filters found for survey.",
    "E019": "Composite could not be calculated: no items found.",
    "E020": "Could not find composite.",
    "E021": "There are no composites for this survey.",
    "E022": "There are no responses to this survey, yet.",
    "E023": "Survey is not active.",
    "E024": "Survey has not started accepting responses.",
    "E025": "Survey no longer accepts responses.",
    "E026": "Survey response not found.",
    "E027": "Could not calculate composite.",
    "E028": "There are no mapped questions to build aggregates on.",
    "E029": "Survey has no composite groups.",
    "E030": "Composite group does not exist.",
    "E031": "You do not have permission to perform this task.",
    "E032": "Could not close the survey",
    "E033": "Could not reach source plugin: operation failed.",
    "E034": "Incorrect credentials",
    "E035": "Validation error: missing or incorrect inputs received.",
    "E036": "Error create item, please see details.",
    "E037": "Failed to import survey from plugin source",
    "E038": "Could not create survey group: see internal logs.",
    "E039": "Survey does not contain any questions.",
    "E040": "Plugin does not found.",
    "E041": "Error creating composite: see internal logs.",
    "E042": "Minimum of two numerator questions required per composite.",
    "E043": "Could not perform update: please see internal logs.",
    "E044": "Could not perform delete: please see internal logs.",
    "E045": "Could not make question group private: please see internal logs.",
    "E046": "An active import is already running for this survey.",
    "E047": "No active action detected for survey.",
    "E048": "The process of closing this survey is already unway. Please wait until it completes.",
}
