module.exports = {
    "accept_responses": "",
    "action_failed": "",
    "active": "",
    "agree_and_continue": "",
    "aggregates": "Porównanie ankiet",
    "aggregates_not_found": "Nie znaleźliśmy żadnych danych zagregowanych dla tej grupy ankiet! Upewnij się, że pytania zostały zmapowane między ankietami.",
    "all": "",
    "answer": "Odpowiedź",
    "answer_label": "",
    "answered": "Odpowiedział",
    "apply": "Zastosować",
    "audit": "Rewizja",
    "audit_desktop_only": "Informacje dotyczące audytu są złożone i jako takie są dostępne tylko na komputerach stacjonarnych.",
    "available_surveys": "Dostępne ankiety",
    "available_survey_data": "Dostępne dane ankiety",
    "background_color": "",
    "back_to_app": "",
    "blockchain_hash_summary": "Podsumowanie Hash Blockchain",
    "button_composite_create": "",
    "button_composite_group_create": "",
    "button_survey_create": "",
    "button_survey_group_create": "",
    "cache": "",
    "cache_warning": "",
    "calculate_composite": "Obliczanie kompozytu, proszę czekać ...",
    "close_active": "",
    "cancel": "",
    "composites_all": "Wszystkie kompozyty",
    "composite_overall_score": "Ogólna ocena kompozytowa",
    "composite": [
        "Złożony",
        "Kompozyty",
    ],
    "composite_group": [
        "",
        ""
    ],
    "concluded": "",
    "confirm_details": "",
    "custom_url": "",
    "cutoff": "",
    "data_point": [
        "",
        "",
    ],
    "data_source_id": "",
    "date_start": "",
    "date_end": "",
    "date_range_description": "",
    "date_recorded": "Data nagrania",
    "delete": "",
    "description": "",
    "details_additional": "",
    "edit": "",
    "enter_details": "",
    "filters": "Filtry",
    "formula": "",
    "icon": "",
    "import_active": "",
    "include_in_numerator_set": "",
    "invalidate": "",
    "landing_image": "",
    "landing_image_description": "",
    "listener_url": "",
    "loading": "Ładowanie",
    "login": "",
    "logout": "",
    "next_step": "",
    "make_private": "",
    "make_public": "",
    "meancutoff_error": "",
    "merkle_root": "Merkle Root",
    "misc": "",
    "name": "",
    "nothing_to_reorder": "",
    "question": [
        "",
        "",
    ],
    "question_group": [
        "",
        "",
    ],
    "questions_all": "Wszystkie pytania",
    "no": "",
    "none": "",
    "numerator": [
        "",
        "",
    ],
    "password_input_placeholder": "Wprowadź hasło dostępu",
    "please_wait": "",
    "preview": "",
    "previous": "",
    "privacy": "",
    "private_content": "",
    "responses": "Odpowiedzi",
    "reponses_import": "",
    "save": "",
    "select_data_point_to_add": "",
    "setting": [
        "",
        "",
    ],
    "source": "Źródło",
    "source_id": "Identyfikacja źródła",
    "source_plugin": "",
    "status": "",
    "submit": "Zatwierdź",
    "success": "",
    "survey_import_warning": "",
    "survey": [
        "",
        "",
    ],
    "survey_add_new": "",
    "survey_group": [
        "",
        "",
    ],
    "survey_close": "",
    "survey_comparison": "Ankieta do porównań ankiet",
    "survey_recent": "",
    "title": [
        "",
        "",
    ],
    "transaction": "Transakcja",
    "unique_url_name": "",
    "warning": "",
    "view_full_survey": "Zobacz pełną ankietę",
    "view_survey": "View Survey",
    "view_survey_group": "",
    "yes": "",
}
