module.exports = {
    /**
     * General Translations (taken from Google Translate)
     */
    "accept_responses": "Zaakceptować odpowiedzi?",
    "action_failed": "Nie udało się wykonać żądanej czynności.",
    "active": "Aktywny",
    "agree_and_continue": "Rozumiem i chcę kontynuować",
    "aggregates": "Porównanie ankiet",
    "aggregates_not_found": "Nie znaleźliśmy żadnych danych zagregowanych dla tej grupy ankiet! Upewnij się, że pytania zostały zmapowane między ankietami.",
    "all": "Wszystko",
    "answer": "Odpowiedź",
    "answer_distribution": "Dystrybucja odpowiedzi",
    "answer_label": "Etykieta odpowiedzi",
    "answered": "Odpowiedział",
    "apply": "Zastosować",
    "audit": "Rewizja",
    "audit_desktop_only": "Informacje dotyczące audytu są złożone i jako takie są dostępne tylko na komputerach stacjonarnych.",
    "available_surveys": "Dostępne ankiety",
    "available_survey_data": "Dostępne dane ankiety",
    "background_color": "Kolor tła",
    "back_to_app": "Powrót do aplikacji",
    "blockchain_hash_summary": "Podsumowanie Hash Blockchain",
    "button_composite_create": "Nowy kompozyt",
    "button_composite_group_create": "Nowa grupa złożona",
    "button_survey_create": "Nowa ankieta",
    "button_survey_group_create": "Nowa grupa ankietowa",
    "cache": "Pamięć podręczna",
    "cache_warning": "Kliknij poniższy przycisk, aby unieważnić pamięć podręczną. Należy pamiętać, że może to odwrotnie zmienić wydajność.",
    "calculate_composite": "Obliczanie kompozytu, proszę czekać ...",
    "cancel": "Anuluj",
    "close_active": "Zamknięcie ankiety aktywne...",
    "composites_all": "Wszystkie kompozyty",
    "composite_overall_score": "Ogólna ocena kompozytowa",
    "composite": [
        "Złożony",
        "Kompozyty",
    ],
    "composite_group": [
        "Grupa złożona",
        "Grupy złożone"
    ],
    "concluded": "Zakończone",
    "confirm_details": "Potwierdź swoje dane poniżej.",
    "custom_url": "Niestandardowy adres URL",
    "cutoff": "Odciąć",
    "data_point": [
        "Punkt danych",
        "Punkty danych",
    ],
    "data_source_id": "Identyfikator ankiety źródła danych",
    "date_start": "Zacznij akceptować Odpowiedziano dnia",
    "date_end": "Przestań akceptować Odpowiedzi w dniu",
    "date_range_description": "Wybierz zakres dat, w którym ankieta będzie aktywna, zbierając odpowiedzi. Odpowiedzi otrzymane poza tym zakresem dat nie będą rejestrowane.",
    "date_recorded": "Data nagrania",
    "date_received_by_sa": "Zaimportowano odpowiedź",
    "date_received_by_blockchain": "Zarejestrowano odpowiedź",
    "delete": "Usunąć",
    "description": "Opis",
    "details_additional": "Wprowadź dodatkowe szczegóły.",
    "edit": "Edytować",
    "enter_details": "Wprowadź żądane dane.",
    "filters": "Filtry",
    "formula": "Formuła",
    "icon": "Ikona",
    "import_active": "Importuj aktywny...",
    "include_in_numerator_set": "Uwzględnij w zestawie liczników",
    "invalidate": "Unieważnić",
    "landing_image": "Obraz strony docelowej",
    "landing_image_description": "Link do obrazu w formacie JPG, PNG nie większym niż 1200x500 pikseli w skali.",
    "listener_url": "URL odbiornika",
    "loading": "Ładowanie",
    "login": "Zaloguj sie",
    "logout": "Wyloguj",
    "make_private": "Ustawienie tego jako prywatnego spowoduje ukrycie go przed wszystkimi czytającymi tę stronę, w tym przed Tobą. Można to odwrócić na stronie ustawień. Czy na pewno chcesz kontynuować?",
    "make_public": "Upublicznij",
    "meancutoff_error": "Wartość odcięcia jest poniżej wartości minimalnej. Proszę zmień.",
    "merkle_root": "Merkle Root",
    "misc": "Różne",
    "name": "Imię",
    "next_step": "Następny krok",
    "no": "Nie",
    "none": "Żaden",
    "nothing_to_reorder": "Nie ma nic do ponownego zamówienia!",
    "numerator": [
        "Licznik ułamka",
        "Liczniki",
    ],
    "password_input_placeholder": "Wprowadź hasło dostępu",
    "please_wait": "Proszę czekać, to może chwilę potrwać...",
    "preview": "Zapowiedź",
    "previous": "Poprzedni",
    "privacy": "Prywatność",
    "private_content": "Następująca treść została oznaczona jako \"prywatna\". Możesz to zmienić poniżej.",
    "question": [
        "Pytanie",
        "pytania",
    ],
    "question_group": [
        "Grupa pytań",
        "Grupy pytań",
    ],
    "questions_all": "Wszystkie pytania",
    "responses": "Odpowiedzi",
    "reponses_import": "Importuj odpowiedzi",
    "save": "Zapisać",
    "select_data_point_to_add": "Wybierz pytanie, które chcesz dodać do kompozytu...",
    "setting": [
        "Oprawa",
        "Ustawienia",
    ],
    "source": "Źródło",
    "source_id": "Identyfikacja źródła",
    "source_plugin": "Wtyczka źródłowa",
    "status": "Status",
    "submit": "Zatwierdź",
    "success": "Sukces",
    "survey": [
        "Ankieta",
        "Ankiety",
    ],
    "survey_add_new": "Dodaj nową ankietę do grupy",
    "survey_group": [
        "Grupa ankietowa",
        "Grupy ankietowe",
    ],
    "survey_close": "Zamknij ankietę",
    "survey_comparison": "Ankieta do porównań ankiet",
    "survey_import_warning": "Jeśli źródło danych zawiera odpowiedzi, które chcesz zaimportować, zrób to poniżej. Pamiętaj, że ukończenie tego procesu może zająć do KILKU GODZIN, podczas których BADANIA NA ŻYWO i / lub AKCEPTACJA DANYCH W CZASIE RZECZYWISTYM mogą BYĆ NIEPOŻĄDANE.",
    "survey_recent": "Najnowsze ankiety",
    "title": [
        "Tytuł",
        "Tytuły",
    ],
    "transaction": "Transakcja",
    "unique_url_name": "Utwórz unikalną nazwę dla linku do panelu.",
    "view_full_survey": "Zobacz pełną ankietę",
    "view_survey": "Wyświetl ankietę",
    "view_survey_group": "Wyświetl grupę ankietową",
    "warning": "Ostrzeżenie",
    "yes": "Tak",

    /**
     * Error Codes
     */
    "E001": "Generic error, no additional details.",
    "E002": "Survey not found.",
    "E003": "Could not find plugin.",
    "E004": "Survey creation error: does the survey already exist or are required fields missing?",
    "E005": "Survey group not found.",
    "E006": "Error creating survey group.",
    "E007": "Could not register survey response.",
    "E008": "Incorrect survey code.",
    "E009": "Could not find question.",
    "E010": "Could not find survey.",
    "E011": "Survey does not contain any groups.",
    "E012": "Could not find question group.",
    "E013": "Question group does not contain any questions.",
    "E014": "Password is required.",
    "E015": "Incorrect password.",
    "E016": "You cannot access this question's data.",
    "E017": "Error normalizing survey data.",
    "E018": "No filters found for survey.",
    "E019": "Composite could not be calculated: no items found.",
    "E020": "Could not find composite.",
    "E021": "There are no composites for this survey.",
    "E022": "There are no responses to this survey, yet.",
    "E023": "Survey is not active.",
    "E024": "Survey has not started accepting responses.",
    "E025": "Survey no longer accepts responses.",
    "E026": "Survey response not found.",
    "E027": "Could not calculate composite.",
    "E028": "There are no mapped questions to build aggregates on.",
    "E029": "Survey has no composite groups.",
    "E030": "Composite group does not exist.",
    "E031": "You do not have permission to perform this task.",
    "E032": "Could not close the survey",
    "E033": "Could not reach source plugin: operation failed.",
    "E034": "Incorrect credentials",
    "E035": "Validation error: missing or incorrect inputs received.",
    "E036": "Error create item, please see details.",
    "E037": "Failed to import survey from plugin source",
    "E038": "Could not create survey group: see internal logs.",
    "E039": "Survey does not contain any questions.",
    "E040": "Plugin does not found.",
    "E041": "Error creating composite: see internal logs.",
    "E042": "Minimum of two numerator questions required per composite.",
    "E043": "Could not perform update: please see internal logs.",
    "E044": "Could not perform delete: please see internal logs.",
    "E045": "Could not make question group private: please see internal logs.",
    "E046": "An active import is already running for this survey.",
    "E047": "No active action detected for survey.",
    "E048": "The process of closing this survey is already unway. Please wait until it completes.",
}
