module.exports = {
    /**
     * General Translations
     */
    "accept_responses": "",
    "action_failed": "",
    "active": "",
    "agree_and_continue": "",
    "aggregates": "Porównanie ankiet",
    "aggregates_not_found": "Nie znaleźliśmy żadnych danych zagregowanych dla tej grupy ankiet! Upewnij się, że pytania zostały zmapowane między ankietami.",
    "all": "",
    "answer": "Odpowiedź",
    "answer_distribution": "",
    "answer_label": "",
    "answered": "Odpowiedział",
    "apply": "Zastosować",
    "audit": "Rewizja",
    "audit_desktop_only": "Informacje dotyczące audytu są złożone i jako takie są dostępne tylko na komputerach stacjonarnych.",
    "available_surveys": "Dostępne ankiety",
    "available_survey_data": "Dostępne dane ankiety",
    "background_color": "",
    "back_to_app": "",
    "blockchain_hash_summary": "Podsumowanie Hash Blockchain",
    "button_composite_create": "",
    "button_composite_group_create": "",
    "button_survey_create": "",
    "button_survey_group_create": "",
    "cache": "",
    "cache_warning": "",
    "calculate_composite": "Obliczanie kompozytu, proszę czekać ...",
    "close_active": "",
    "cancel": "",
    "composites_all": "Wszystkie kompozyty",
    "composite_overall_score": "Ogólna ocena kompozytowa",
    "composite": [
        "Złożony",
        "Kompozyty",
    ],
    "composite_group": [
        "",
        ""
    ],
    "concluded": "",
    "confirm_details": "",
    "custom_url": "",
    "cutoff": "",
    "data_point": [
        "",
        "",
    ],
    "data_source_id": "",
    "date_start": "",
    "date_end": "",
    "date_range_description": "",
    "date_recorded": "Data nagrania",
    "date_received_by_sa": "",
    "date_received_by_blockchain": "",
    "delete": "",
    "description": "",
    "details_additional": "",
    "edit": "",
    "enter_details": "",
    "filters": "Filtry",
    "formula": "",
    "icon": "",
    "import_active": "",
    "include_in_numerator_set": "",
    "invalidate": "",
    "landing_image": "",
    "landing_image_description": "",
    "listener_url": "",
    "loading": "Ładowanie",
    "login": "",
    "logout": "",
    "next_step": "",
    "make_private": "",
    "make_public": "",
    "meancutoff_error": "",
    "merkle_root": "Merkle Root",
    "misc": "",
    "name": "",
    "nothing_to_reorder": "",
    "question": [
        "",
        "",
    ],
    "question_group": [
        "",
        "",
    ],
    "questions_all": "Wszystkie pytania",
    "no": "",
    "none": "",
    "numerator": [
        "",
        "",
    ],
    "password_input_placeholder": "Wprowadź hasło dostępu",
    "please_wait": "",
    "preview": "",
    "previous": "",
    "privacy": "",
    "private_content": "",
    "responses": "Odpowiedzi",
    "reponses_import": "",
    "save": "",
    "select_data_point_to_add": "",
    "setting": [
        "",
        "",
    ],
    "source": "Źródło",
    "source_id": "Identyfikacja źródła",
    "source_plugin": "",
    "status": "",
    "submit": "Zatwierdź",
    "success": "",
    "survey_import_warning": "",
    "survey": [
        "",
        "",
    ],
    "survey_add_new": "",
    "survey_group": [
        "",
        "",
    ],
    "survey_close": "",
    "survey_comparison": "Ankieta do porównań ankiet",
    "survey_recent": "",
    "title": [
        "",
        "",
    ],
    "transaction": "Transakcja",
    "unique_url_name": "",
    "warning": "",
    "view_full_survey": "Zobacz pełną ankietę",
    "view_survey": "View Survey",
    "view_survey_group": "",
    "yes": "",

    /**
     * Error Codes
     */
    "E001": "Generic error, no additional details.",
    "E002": "Survey not found.",
    "E003": "Could not find plugin.",
    "E004": "Survey creation error: does the survey already exist or are required fields missing?",
    "E005": "Survey group not found.",
    "E006": "Error creating survey group.",
    "E007": "Could not register survey response.",
    "E008": "Incorrect survey code.",
    "E009": "Could not find question.",
    "E010": "Could not find survey.",
    "E011": "Survey does not contain any groups.",
    "E012": "Could not find question group.",
    "E013": "Question group does not contain any questions.",
    "E014": "Password is required.",
    "E015": "Incorrect password.",
    "E016": "You cannot access this question's data.",
    "E017": "Error normalizing survey data.",
    "E018": "No filters found for survey.",
    "E019": "Composite could not be calculated: no items found.",
    "E020": "Could not find composite.",
    "E021": "There are no composites for this survey.",
    "E022": "There are no responses to this survey, yet.",
    "E023": "Survey is not active.",
    "E024": "Survey has not started accepting responses.",
    "E025": "Survey no longer accepts responses.",
    "E026": "Survey response not found.",
    "E027": "Could not calculate composite.",
    "E028": "There are no mapped questions to build aggregates on.",
    "E029": "Survey has no composite groups.",
    "E030": "Composite group does not exist.",
    "E031": "You do not have permission to perform this task.",
    "E032": "Could not close the survey",
    "E033": "Could not reach source plugin: operation failed.",
    "E034": "Incorrect credentials",
    "E035": "Validation error: missing or incorrect inputs received.",
    "E036": "Error create item, please see details.",
    "E037": "Failed to import survey from plugin source",
    "E038": "Could not create survey group: see internal logs.",
    "E039": "Survey does not contain any questions.",
    "E040": "Plugin does not found.",
    "E041": "Error creating composite: see internal logs.",
    "E042": "Minimum of two numerator questions required per composite.",
    "E043": "Could not perform update: please see internal logs.",
    "E044": "Could not perform delete: please see internal logs.",
    "E045": "Could not make question group private: please see internal logs.",
    "E046": "An active import is already running for this survey.",
    "E047": "No active action detected for survey.",
    "E048": "The process of closing this survey is already unway. Please wait until it completes.",
}
