export const ACCESS_LEVEL_CHANGE = "ACCESS_LEVEL_CHANGE";
export const ACTIVE_SURVEY_CHANGE = "ACTIVE_SURVEY_CHANGE";
export const BUILD_BREADCRUMBS = "BUILD_BREADCRUMBS";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const FILTER_CHANGE_SUBMIT = "FILTER_CHANGE_SUBMIT";
export const TOGGLE_MENU = "TOGGLE_MENU";